### ISSUE TITLE
Change date formatting to a more standard one

### ISSUE THREAD

**Issue by emredjan** [jupyter-xeus/xeus-sql#39]
Hi, the formatting of the date / datetime columns in the displayed tables are offloaded to `asctime()` function as stated [here](https://github.com/jupyter-xeus/xeus-sql/blob/feb3bc5ba5406798ede30af739d8acc9bec14960/src/xeus_sql_interpreter.cpp#L133), which displays the dates as a very non-standard way (`Www Mmm dd hh:mm:ss yyyy\n`),

The display can be done using `strftime()` instead to display these columns in an ISO compatible format (i.e `yyyy-mm-dd hh:mm:ss`).  My C++ skills is not good enough to come up with a PR for this but I'm assuming it's not a complicated change.

Also, if SOCI supports distinguishing `date` and `datetime` columns, time display portion can be stripped from `date` columns as well.

**Comment by marimeireles** [comment]
Hey @emredjan, good catch! Thanks for the issue.
This one I can do :)
Already fixed it, now I'm thinking this might be a breaking change for other people and it'd be better to release a bigger version for this. I need to release a new version of SOCI to be able to release a new version of `xeus-sql`. Hope to have this stuff done by the end of the day.
Thanks again :cherry_blossom:

**Comment by emredjan** [comment]
Thanks, Maria, but I don't think it worked as you intended. Now date columns come empty with version 0.1.0:
![image](https://user-images.githubusercontent.com/389091/121335434-e0a25600-c91a-11eb-9454-68b68fcd450f.png)

**Comment by marimeireles** [comment]
hum! sorry for that, I'm pretty sure it was working locally! :/
I'll put it on my list to have a look, will try to do it today, thanks for pinging here again.

**Comment by marimeireles** [comment]
Hi @emredjan, I had a look yesterday and it's working normally for me.

It's also working on the binder instance:

![image](https://user-images.githubusercontent.com/17600982/121521064-262a5600-c9e3-11eb-8263-680fc817c20b.png)

Which makes me believe might be some dependency problem. If you can I advise you to be completely inside the conda environment and not allow pip or system packages to interfere with the conda packages. If you're building it from source I advise downloading `mamba install cmake compilers`.

Maybe a list of what I have in my environment for you to check helps: https://pastebin.com/j5CB3rdY (there's prbb a bunch of things there you don't need)

Please let me know if I can help with something else on how to debug this... What's the OS you're using?

**Comment by emredjan** [comment]
Thanks @marimeireles for checking.

That command indeed works as intended on my end as well, but selecting a date column from a table shows blank:

![image](https://user-images.githubusercontent.com/389091/121527143-634e1280-c9fa-11eb-81d8-6d3eee512ad8.png)

You can test for yourself:

```sql
select datetime('now', 'localtime')

--drop table test1

create table test1
(
    date_col datetime,
    dummy_col nvarchar(10)
)

insert into test1
values
    (datetime('now', 'localtime'), 'dummy')

select * from test1
```

Or just `select * from employees` with the example `chinook.db`:

![image](https://user-images.githubusercontent.com/389091/121527426-af995280-c9fa-11eb-982e-fa29ff416efa.png)

It's reproducible in all these configs:

- Windows 10 / Microsoft SQL Server 2017 (via ODBC)
- Windows 10 / SQLite
- RHEL 8 / Microsoft SQL Server 2017 (via ODBC)
- RHEL 8 / SQLite

Although, not even date functions return properly in SQL Server:

![image](https://user-images.githubusercontent.com/389091/121527762-0c950880-c9fb-11eb-888f-dd55b753506c.png)

**Comment by emredjan** [comment]
> Maybe a list of what I have in my environment for you to check helps: https://pastebin.com/j5CB3rdY (there's prbb a bunch of things there you don't need)

That environment shows `xeus-sql` is still at version 0.0.8? This blank date issue started at 0.1.0. Or is that your development package?

**Comment by marimeireles** [comment]
>That environment shows xeus-sql is still at version 0.0.8? This blank date issue started at 0.1.0. Or is that your development package?

That's true! Sorry I didn't pay attention to this. I thought I was running the build version and not the conda one, and thanks for supplying examples, will look into it now :)

**Comment by emredjan** [comment]
Also, please do not use the sqlite `select datetime('now', 'localtime')` function for testing, as the value it returns is a `text` already in iso format, not a `datetime`, so it's not relevant to this.

> The SQLite datetime() function takes datetimestring & one or more modifier values and returns date and time in YYYY-MM-DD HH:MM:SS format. It is important to note that this function will return the TEXT as an output.

See: https://www.tutlane.com/tutorial/sqlite/sqlite-datetime-function

**Comment by marimeireles** [comment]
@emredjan uhright
Thanks for opening the issue and giving me examples!
Should be fixed now! :)

**Comment by marimeireles** [comment]
Soon a new conda-forge version will come up, it takes a little bit for the changes to take effect. For the next hours if you want to test you must build it from source.

**Comment by emredjan** [comment]
> Soon a new conda-forge version will come up, it takes a little bit for the changes to take effect. For the next hours if you want to test you must build it from source

It's 17:00 on a Friday here, I'm gonna give it a rest until Monday, hopefully the conda-forge package will be up by then :)

**Comment by emredjan** [comment]
Thanks @marimeireles it works now, with one caveat:

You defined the date formatting as `"%Y-%m-%e %H:%M:%S"` where `%e` is the day of the month, with _space_-padding. However it would be more correct, iso-compatible and consistent with the other parts of the date if you used `%d` day of the month, with _zero_-padding. 

Now it looks a bit weird 🤔

![image](https://user-images.githubusercontent.com/389091/121902232-6cefb700-cd27-11eb-902b-b9a1bd266eb0.png)

**Comment by marimeireles** [comment]
Huh, I didn't notice that, I'll look for a solution for this :)
Glad it's working!

**Comment by emredjan** [comment]
Created #44 for this.
