### ISSUE TITLE
Add syntax completion to SQL

### ISSUE THREAD

**Issue by marimeireles** [jupyter-xeus/xeus-sql#53]
Thorsten lovely added syntax completion for SQLite and I think we could do something very similar to his PR on xeus-SQL. We just need to make sure the keywords are universal, I guess, because otherwise it will recommend invalid words for invalid sub SQL languages.

This is a good issue for someone who'd like to contribute for the first time, let me know if you have any questions.

**Comment by DerThorsten** [comment]
this can a starting point https://github.com/jupyter-xeus/xeus-sql/pull/54

only the list of actual keywords needs to be changed .
maybe this list needs to be conditioned on `USE_POSTGRE_SQL` / `USE_MYSQL` / `USE_SQLITE3`

**Comment by marimeireles** [comment]
> maybe this list needs to be conditioned on USE_POSTGRE_SQL / USE_MYSQL / USE_SQLITE3

Yes, this is the source for the [original list](https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words)

**Comment by marimeireles** [comment]
closed by #56
