### ISSUE TITLE
"money" column type in Postgresql generating error

### ISSUE THREAD

**Issue by mzeidenberg** [jupyter-xeus/xeus-sql#56]
Hi, I have just installed xeus-sql and am using it with Postgresql. It is generating an error when I try to access Postgresql columns of type "money" in select statements. This is the error I'm getting:

Error: unknown data type with typelem: 790 for colNum: 7 with name: budget while executing "select * from movie".

"budget" is one of the two columns in this "movie" table that are of type money. It is a small table of data about some movies that we use for teaching.

I can get around this by casting the column to numeric when I use it.

Thanks.

**Comment by marimeireles** [comment]
Hey @mzeidenberg, sorry to spend so long to reply, I was out of the web and missed it after I immediately came back.

I didn't know this type and looking into SOCI documentation and code there's no implementation for that in there. Meaning, this might be an issue for [upstream](https://github.com/SOCI/soci). I suspect we're missing this type entirely, sorry!

**Comment by marimeireles** [comment]
Closing as upstream, sorry!
