### ISSUE TITLE
Kernel crashes with `terminate called after throwing an instance of 'char const*'`

### ISSUE THREAD

**Issue by yuvipanda** [jupyter-xeus/xeus-sql#60]
@jameshowison is using this kernel for some of his classes, connecting to postgres over localhost. However, kernels are often crashing, and looking at the logs shows this error message:

`terminate called after throwing an instance of 'char const*'``

Doesn't actually tell us what was the value of the error message, nor a traceback - which I'm guessing will help us see what is actually happening.

https://github.com/2i2c-org/infrastructure/issues/968 has more context.

**Comment by JohanMabille** [comment]
xeus-sql only throws a string [here](https://github.com/jupyter-xeus/xeus-sql/blob/3628e03ec5bad90fe283474259f58b31a3814855/src/xeus_sql_interpreter.cpp#L332) so I guess the issue is that it could not load the database.

I will add better error handling though, maybe this can be thrown by a dependency of xeus-sql.

**Comment by JohanMabille** [comment]
@yuvipanda @jameshowison I've just tagged a release, I'm preparing the conda package, it should be available in a few hours.

**Comment by yuvipanda** [comment]
@JohanMabille yay, thank you :)

**Comment by yuvipanda** [comment]
@JohanMabille I see xeus-sql 0.1.5 in https://anaconda.org/conda-forge/xeus-sql but my builds are still failing (https://github.com/2i2c-org/utexas-image/runs/5302618142?check_suite_focus=true) with the version not being found. Do you know if this is a cache issue?

**Comment by JohanMabille** [comment]
Yes sometimes it can takes a wihle before the package is replicated on all the mirrors.

**Comment by yuvipanda** [comment]
@JohanMabille i think it's done now!
