### ISSUE TITLE
Display number of results at top of output, rather than bottom?

### ISSUE THREAD

**Issue by jameshowison** [jupyter-xeus/xeus-sql#62]
When writing queries it's often useful to get a feel for the number of results (without specifically writing a COUNT(*) bit).  Currently the number of rows is at the bottom which means lots of scrolling to see (for any decent size of results).  

Could the number of results line come at the top?  (That would also combine well with paging results :)

**Comment by marimeireles** [comment]
That's reasonable :)

**Comment by marimeireles** [comment]
This is also relatively simple... With an ugly solution but will work.
You can filter count results and use STD to order the results.
