### ISSUE TITLE
postgres first line comment shows no results

### ISSUE THREAD

**Issue by jameshowison** [jupyter-xeus/xeus-sql#63]
It seems that having a `--` comment on the first line of a cell causes no result to be displayed by postgres.  e.g.,

```
-- new query
SELECT *
FROM pg_catalog.pg_tables;
```

Shows no result,. but 

```
SELECT *
FROM pg_catalog.pg_tables;
-- new query
```

Shows results.

**Comment by marimeireles** [comment]
This is easy to fix!
I'll open a PR...
There's so much stuff I want to rewrite in this software though! 😅
